name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["bug"]
assignees: 
  - PaulleDemon
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: template-name
    attributes:
      label: Template name
      description: Please tell us which template is the issue related to
      placeholder: Template name
      value: "Template name"
    validations:
        required: true

  - type: input
    id: browser
    attributes:
      label: Browser & version
      description: Please tell us which browser and version of the browser you are using
      placeholder: Browser name & version
      value: "Browser name"
    validations:
        required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
        required: true

  - type: checkboxes
    id: related-issues
    attributes:
      label: This is a new issue
      description: I have checked for the same issue in the issues panel
      options:
        - label: "Yes"
          required: true
